[package]
name = "buka"
version = "0.0.1-alpha"
edition = "2021"

[dependencies]
clap = { workspace = true }
libloading = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }